### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zaniyahh** [AtjonTV/ZeusBot#2]
2018-06-14 10:42:57,365 [MainThread][      main][ WARNING] Debugging is enabled!
2018-06-14 10:43:01,243 [MainThread][      main][    INFO] You have 0 of 30 tasks running.
2018-06-14 10:43:04,829 [MainThread][     utils][   ERROR] Error: HTTP Error 500: Internal Server Error
2018-06-14 10:43:04,829 [MainThread][     utils][    INFO] Timeout while requesting "vh_updateInfo.php"
2Traceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 882, in emit
    stream.write(fs % msg)
IOError: [Errno 0] Error
Logged from file utils.py, line 162
2018-06-14 10:43:09,592 [MainThread][     utils][    INFO] Timeout while requesting "vh_updateInfo.php"
2018-06-14 10:43:12,459 [MainThread][     utils][   ERROR] Error: HTTP Error 500: Internal Server Error
2018-06-14 10:43:12,459 [MainThread][     utils][    INFO] Timeout while requesting "vh_updateInfo.php"

**Comment by AtjonTV** [comment]
## About Support
Sorry, [ZeusBot](http://wiki.osmium.software/index.php/ZeusBot) is no longer supported by us (ATVG-Studios).

If you look into our [wiki](http://wiki.osmium.software/index.php/ZeusBot), you will see that [ZeusBot](http://wiki.osmium.software/index.php/ZeusBot) is a [STS](http://wiki.osmium.software/index.php/Software_Support_Cycles)(Short Term Support) release, that means we only give support for half a year (6 months).

The support is from **December 2017** until **June 2018**, as I see you created the issue 10 days ago (14th June 2018), so the support is already over.

Besides that [vHackXT](http://wiki.osmium.software/index.php/vHackXT) is also no longer developed by KF-Media.

## About Issue
As it looks, the bot doesn't have any issues .. the issue comes from the server: `Error: HTTP Error 500: Internal Server Error`.

You can try to reset the config and/or login with another account.  
If that wont fix the issue, it is a server issue and cant be fixed by us.

Also this stacktrace:

```
2Traceback (most recent call last):
File "C:\Python27\lib\logging_init_.py", line 882, in emit
stream.write(fs % msg)
IOError: [Errno 0] Error
```

shows a issue comming from a python 2.7 library/module, so we also cant help on that ..

## About vHackOS
If you decide to play [vHackOS](http://wiki.osmium.software/index.php/VHackOS) or bot it, you can checkout [PlatinumBot](http://wiki.osmium.software/index.php/PlatinumBot), it is also a [STS](http://wiki.osmium.software/index.php/Software_Support_Cycles)(Short Term Support) release.

[PlatinumBot](http://wiki.osmium.software/index.php/PlatinumBot) is supported from **April 2018** until **October 2018**.

[PlatinumBot](http://wiki.osmium.software/index.php/PlatinumBot) is still in some sort of development by us.

Besides that [vHackOS](http://wiki.osmium.software/index.php/VHackOS) is still in development and supported by KF-Media.

**Comment by AtjonTV** [comment]
Here is a little update on vHackOS Bots:

The support and development of PlatinumBot has ended with todays date (7th October 2018).

But! There is a bot out there that is still up-to-date and still in active development, it's name is [vhackos-b0tnet](https://gitlab.com/OphiteCorp/H4ck1t/vhackos-b0tnet). It is fully open-source and according to feedback on Discord it works great!
